auto:	          true

markdown:         rdiscount
pygments:         true
paginate:         6
permalink:        /:title

title:            ncRNA.net
url:              http://ncrna.net
feed:             /atom.xml
author:
    name:         NCRNA
    twitter:      twitter.com
description:      "NCRNA\'s Blog"
author_info:      <a href="http://ncrna.net/about">NCRNA</a>

copyright:
    - Design by <a href="http://ncrna/about" title="NCRNA" target="_blank">NCRNA</a> &copy; Copyright 2012
